//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Resources/actions/customactions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Customactions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Customactions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""customactions"",
    ""maps"": [
        {
            ""name"": ""rightclick"",
            ""id"": ""dfdb750a-ecc3-4f07-8019-c14e5609bca7"",
            ""actions"": [
                {
                    ""name"": ""clickmove"",
                    ""type"": ""Button"",
                    ""id"": ""3c874341-e872-4610-8cc8-49c771122580"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""949f9ac8-a43e-4a5e-9c22-2f0fb724a53f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""clickmove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // rightclick
        m_rightclick = asset.FindActionMap("rightclick", throwIfNotFound: true);
        m_rightclick_clickmove = m_rightclick.FindAction("clickmove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // rightclick
    private readonly InputActionMap m_rightclick;
    private List<IRightclickActions> m_RightclickActionsCallbackInterfaces = new List<IRightclickActions>();
    private readonly InputAction m_rightclick_clickmove;
    public struct RightclickActions
    {
        private @Customactions m_Wrapper;
        public RightclickActions(@Customactions wrapper) { m_Wrapper = wrapper; }
        public InputAction @clickmove => m_Wrapper.m_rightclick_clickmove;
        public InputActionMap Get() { return m_Wrapper.m_rightclick; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightclickActions set) { return set.Get(); }
        public void AddCallbacks(IRightclickActions instance)
        {
            if (instance == null || m_Wrapper.m_RightclickActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightclickActionsCallbackInterfaces.Add(instance);
            @clickmove.started += instance.OnClickmove;
            @clickmove.performed += instance.OnClickmove;
            @clickmove.canceled += instance.OnClickmove;
        }

        private void UnregisterCallbacks(IRightclickActions instance)
        {
            @clickmove.started -= instance.OnClickmove;
            @clickmove.performed -= instance.OnClickmove;
            @clickmove.canceled -= instance.OnClickmove;
        }

        public void RemoveCallbacks(IRightclickActions instance)
        {
            if (m_Wrapper.m_RightclickActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightclickActions instance)
        {
            foreach (var item in m_Wrapper.m_RightclickActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightclickActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightclickActions @rightclick => new RightclickActions(this);
    public interface IRightclickActions
    {
        void OnClickmove(InputAction.CallbackContext context);
    }
}
